name: Create Pull Request from gh-pages to main

on:
  push:
    branches:
      - gh-pages

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "doxsuu@gmail.com"
          git config --global user.name "doxsuu"

      - name: Create Pull Request
        run: |
          BRANCH=$(git branch --show-current)
          if [ "$BRANCH" != "main" ]; then
            git push -f origin HEAD:main
            gh pr create --title "Automated PR from gh-pages to main" --base main --head gh-pages --body "Automatically created PR from gh-pages branch."
          else
            echo "Skipping PR creation as it's on the main branch."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
