name: Create Pull Request from gh-pages to main

on:
  push:
    branches: '*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "doxsuu@gmail.com"
          git config --global user.name "doxsuu"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Automated PR from gh-pages to main
          body: Automatically created PR from gh-pages branch.
          branch: gh-pages
          base: main
